/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-09-17 01:23:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");

	int boardNumber = 0;
	int groupNumber = 1;
	int sequenceNumber =0;
	int sequenceLevel=0;
	
	if(request.getParameter("boardNumber")!=null){
		boardNumber=Integer.parseInt(request.getParameter("boardNumber"));
		groupNumber=Integer.parseInt(request.getParameter("groupNumber"));
		sequenceNumber=Integer.parseInt(request.getParameter("sequenceNumber"));
		sequenceLevel=Integer.parseInt(request.getParameter("sequenceLevel"));
	}
	
	out.print(boardNumber + groupNumber + sequenceNumber + sequenceLevel);
	

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" />\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\" src=\"script.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div align=\"center\">\n");
      out.write("\t\t<form class=\"border_doc\" action=\"writeOk.jsp\" method=\"post\"\n");
      out.write("\t\t\tonsubmit=\"return writeForm(this)\">\n");
      out.write("\t\t\t<div>글쓰기</div>\n");
      out.write("\t\t\t<div style=\"text-align: right; color: red;\">\n");
      out.write("\t\t\t\t<a href=\"\">글목록</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"border_div\">\n");
      out.write("\t\t\t\t<div class=\"border_box_left\" style=\"border-top-width: 1px;\">작성자</div>\n");
      out.write("\t\t\t\t<div class=\"border_box_right\" style=\"border-top-width: 1px;\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"writer\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"border_div\">\n");
      out.write("\t\t\t\t<div class=border_box_left>제목</div>\n");
      out.write("\t\t\t\t<div class=border_box_right>\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"subject\" size=\"40\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"border_div\">\n");
      out.write("\t\t\t\t<div class=\"border_box_left\">이메일</div>\n");
      out.write("\t\t\t\t<div class=\"border_box_right\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"email\" size=\"40\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"border_div\" style=\"height: 300px;\">\n");
      out.write("\t\t\t\t<div class=\"border_box_left\" style=\"height: 300px;\">내용</div>\n");
      out.write("\t\t\t\t<div class=\"border_box_right\" style=\"height: 300px;\">\n");
      out.write("\t\t\t\t\t<textarea name=\"content\" cols=\"67\" rows=\"19\"></textarea>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"border_div\">\n");
      out.write("\t\t\t\t<div class=\"border_box_left\">비밀번호</div>\n");
      out.write("\t\t\t\t<div class=\"border_box_right\">\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"pw\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"border_box\">\n");
      out.write("\t\t\t\t<span><input type=\"submit\" value=\"글쓰기\"></span> <span><input\n");
      out.write("\t\t\t\t\ttype=\"reset\" value=\"다시작성\"></span> <span><input\n");
      out.write("\t\t\t\t\ttype=\"button\" value=\"목록보기\"></span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
