/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-09-16 06:42:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.guest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import guestModel.*;
import java.util.ArrayList;
import java.text.SimpleDateFormat;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");

	int boardSize = 3;
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

      out.write('\n');
      out.write('\n');

	//총 게시물 수
	//페이지당 게시물
	//페이지당 시작번호, 끝번호
	
	String pageNumber=request.getParameter("pageNumber");
	if(pageNumber==null) pageNumber="1";
	int currentPage = Integer.parseInt(pageNumber); // [1]: 1~10
	
	int startRow = (currentPage-1)*boardSize+1;
	int endRow = (currentPage*boardSize);
	
	int count = GuestDao.getInstance().getCount();

	ArrayList<GuestDto> guestList = null;
	if(count>0){
	 	guestList= GuestDao.getInstance().getGuestList(startRow, endRow);
	}

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("   <head>\n");
      out.write("      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\n");
      out.write("      <title>방명록</title>\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\n");
      out.write("      <script type=\"text/javascript\" src=\"script.js\"></script>\n");
      out.write("   </head>\n");
      out.write("   <body>\n");
      out.write("      <div align=\"center\">\n");
      out.write("      \t");
if(currentPage ==1||count==0){ 
      out.write("\n");
      out.write("         <form class=box name=\"writeForm\" action=\"writeOk.jsp\" method=\"post\" onsubmit=\"return writeCheck(this)\">\n");
      out.write("               <div class=div_top>\n");
      out.write("                  <font>이름</font>\n");
      out.write("                  <font><input type=\"text\" name=\"name\"/></font>\n");
      out.write("                  <font>비밀번호</font>\n");
      out.write("                  <font><input type=\"password\" name=\"password\"></font>\n");
      out.write("               </div>\n");
      out.write("               <div class=div_mid>\n");
      out.write("                  <textarea name=\"message\" cols=\"65\" rows=\"10\"></textarea>\n");
      out.write("               </div>\n");
      out.write("               <div class=div_top style=\"text-align:right;\">\n");
      out.write("                  <font><input type=\"submit\" value=\"확인\"></font>\n");
      out.write("                  <font><input type=\"reset\" value=\"취소\"></font>            \n");
      out.write("               </div>                  \n");
      out.write("         </form>\n");
      out.write("         ");
} 
      out.write("\n");
      out.write("         ");
for(int i= 0; i<guestList.size();i++){ 
         	GuestDto list = guestList.get(i);
         
      out.write("\n");
      out.write("\t          <div class=\"box\" style = \"border-width:1px;\">\n");
      out.write("\t               <div class=\"div_top\" style = \"text-align:right; border-width:1px\">\n");
      out.write("\t                  ");
      out.print(list.getName() );
      out.write("\n");
      out.write("\t                  ");
      out.print(sdf.format(list.getWriteDate()) );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("\t                  \n");
      out.write("\t                  <a href = \"update.jsp?num=");
      out.print(list.getNum());
      out.write("\">수정</a>\n");
      out.write("\t                  <a href = \"delete.jsp?num=");
      out.print(list.getNum() );
      out.write("\">삭제</a>\n");
      out.write("\t               </div>\n");
      out.write("\t               \n");
      out.write("\t               <div class=\"div_mid\" style = \"border-width:1px\">\n");
      out.write("\t\t\t\t\t\t");
      out.print(list.getMessage() );
      out.write("\n");
      out.write("\t               </div>\n");
      out.write("\t         </div>\n");
      out.write("         ");
} 
      out.write("\n");
      out.write("      </div>   \n");
      out.write("      <!-- 페이지 -->\n");
      out.write("      ");
if(count>0){ 
	      	int pageBlock = 3;
	    
	      	int pageCount= count/boardSize+(count%boardSize==0?0:1);
	      	
	      	int startPage=(int)((currentPage-1)/pageBlock)*pageBlock+1;
	      	int endPage = startPage+pageBlock-1;
	      	
	      	if(endPage > pageCount)endPage = pageCount;
			
	      	if(startPage>pageBlock){
      out.write("\n");
      out.write("\t      \t\t<a href = \"write.jsp?pageNumber=");
      out.print(startPage-pageBlock);
      out.write("\">[이전]</a>\n");
      out.write("\t      \t\t\n");
      out.write("\t      \t");
} 
      out.write("\n");
      out.write("\t      \t\n");
      out.write("\t      \t");
for(int i=startPage; i<= endPage;i++){
      out.write("\n");
      out.write("\t      \t\t<a href =\"write.jsp?pageNumber=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.write('[');
      out.print(i );
      out.write("]</a>\n");
      out.write("\t      \t");
} 
      out.write("\n");
      out.write("\t      \t\n");
      out.write("\t      \t");
 if(endPage < pageCount){
      out.write("\n");
      out.write("\t      \t\t<a href=\"write.jsp?pageNumber=");
      out.print(startPage+pageBlock);
      out.write("\">[다음]</a>\n");
      out.write("\t      \t");
} 
      out.write("\n");
      out.write("      \t\n");
      out.write("      ");
} 
      out.write("\n");
      out.write("   </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
